// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSL3tkyPzhqDHAudfD5XkfSLT3IiyHnqo',
    appId: '1:54684483623:android:a302f7822437758ce1ce02',
    messagingSenderId: '54684483623',
    projectId: 'u-shop-1f79a',
    storageBucket: 'u-shop-1f79a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_9f5A-0m8N395yrywsIrAbiT0WRJfnY',
    appId: '1:54684483623:ios:7fdd1a1f20657d2ee1ce02',
    messagingSenderId: '54684483623',
    projectId: 'u-shop-1f79a',
    storageBucket: 'u-shop-1f79a.appspot.com',
    androidClientId: '54684483623-5a02ofl2nqk40npo04g921b5tc3ib23u.apps.googleusercontent.com',
    iosClientId: '54684483623-f2rvavf30c9kufqrv9b2vjm1aqnd9hbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ushop',
  );
}
